'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes"
import { Header } from '@/app/(site)/components/header'
import { Footer } from '@/app/(site)/components/footer'
import { SidebarMenu } from "@/app/(site)/components/sidebarMenu";
import { Banner } from "./(site)/components/banner";
import { useState } from "react";
import { AuthProvider } from "./(auth)/context/AuthContext";
import { redirect } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Цивилизация робото организмов",
//   description: "Generated by create next app",
// };

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}


